doctrine:
  dbal:
    types:
      date: PlanB\Framework\Doctrine\DBAL\Type\CarbonDateType
      date_immutable: PlanB\Framework\Doctrine\DBAL\Type\CarbonDateImmutableType
      datetime: PlanB\Framework\Doctrine\DBAL\Type\CarbonDateTimeType
      datetime_immutable: PlanB\Framework\Doctrine\DBAL\Type\CarbonDateTimeImmutableType

      time: PlanB\Framework\Doctrine\DBAL\Type\CarbonTimeType
      time_immutable: PlanB\Framework\Doctrine\DBAL\Type\CarbonTimeImmutableType

      EventId: PlanB\Framework\Doctrine\DBAL\Type\EventIdType

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      PlanBBundle:
        is_bundle: true
        type: xml
        prefix: PlanB\Domain
        dir: 'Resources/config/mapping/doctrine'
        alias: PlanB\Domain
