parameters:
services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  PlanB\Domain\:
    resource: '../../../../src/Domain'

  PlanB\UseCase\:
    resource: '../../../../src/UseCase'

  PlanB\Framework\:
    resource: '../../../../src/Framework'

  # serializer
  planb.serializer.normalizer.carbon:
    class: PlanB\Framework\Api\Normalizer\CarbonNormalizer
    tags:
      - { name: serializer.normalizer, priority: 0 }

  serializer.normalizer.datetime:
    class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
    arguments:
      - !php/const \Symfony\Component\Serializer\Normalizer\DateTimeNormalizer::FORMAT_KEY: 'Y-m-d H:i:s'
    tags:
      - { name: serializer.normalizer, priority: -900 }

  PlanB\Framework\Api\State\Processor\AddHeadersProcessor:
    decorates: "api_platform.state_processor.respond"
    arguments:
      $decorated: "@.inner"
      $etag: '%api_platform.http_cache.etag%'
      $maxAge: '%api_platform.http_cache.max_age%'
      $sharedMaxAge: '%api_platform.http_cache.shared_max_age%'
      $vary: '%api_platform.http_cache.vary%'
      $public: '%api_platform.http_cache.public%'
